name: Log Variance SVM

paradigms:
  - LeftRightImagerySinglePass

pipeline:
  - name: LogVariance
    from: moabb.pipelines.single_pass

  - name: SVC
    from: sklearn.svm
    parameters:
      kernel: 'linear'
